apiVersion: v1
kind: Service
metadata:
    name: svc-kodotiazuredevopsapistag
    labels:
        product: kodotiazuredevopsapistag
spec:
    selector:
        app: app-kodotiazuredevopsapistag
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: dep-kodotiazuredevopsapistag
spec:
    replicas: 1
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: app-kodotiazuredevopsapistag
        spec:
            containers:
            - image: dockerapiatc.azurecr.io/kodotiazuredevopsapi:__Build.BuildId__
              imagePullPolicy: IfNotPresent
              name: kodotiazuredevopsapistag
              ports:
              - containerPort: 80
              env:
              - name: ASPNETCORE_ENVIRONMENT
                value: "Staging"
            imagePullSecrets:
            - name: regsecret